# Site settings
title: UX Academy
email: apirakb@gmail.com
description: >
  UX Academy is a company focusing on User Experience, User Research,
  User Interview, Usability Testing, Data Analytic, Cretique UI.
  Our service is Training, Coaching and UX Consultant.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://uxacademy.github.io" # the base hostname & protocol for your site
twitter_username: apirak
github_username:  uxacademy

# Build settings
markdown: kramdown
